Repository prgrms-fe-devcourse/FEDC4_FTA_JEESEOK, pull requests merged in 2023-09, with the labels that each got.

#46 README 문서 내용을 수정
  README.md
Labels: 문서

#50 feat: #49 Base API 구현
  .gitignore
  src/api/index.ts
Labels: 기능

#52 템플릿 내용 수정
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 기능

#60 베이스 api 프리티어 적용
  src/api/index.ts
Labels: 스타일

#62 feat: #61 API ENDPOINT env 변경
  src/api/index.ts
Labels: 긴급

#73 템플릿 반영을 위한 main 브랜치 머지
  .eslintrc.cjs
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .prettierrc
  README.md
  public/vite.svg
  src/api/index.ts
  src/api/like/index.ts
  src/stories/Button.stories.ts
  src/types/index.ts
  tsconfig.json
  vite.config.ts
Labels: 기능

#69 feat: #56 Comment API 구현
  src/api/comment/index.ts
Labels: 기능

#71 notification API 구현
  src/api/notification/index.ts
Labels: 기능

#65 feat: #58 Post API 추가
  src/api/post1/index.ts
Labels: 기능

#76 사용자와 설정 api 구현
  src/api/settings/index.ts
  src/api/user/index.ts
Labels: 기능

#80 내가 작성한 포스트 수정, 삭제 API 구현
  src/api/post/index.ts
Labels: 기능

#82 사용자 검색, 전체 검색(사용자, 포스트) API 구현
  src/api/search/index.ts
Labels: 기능

#89 공통 api 포맷에 맞춰 api 리펙토링 진행
  src/api/authorization/authorizationCheck.ts
  src/api/authorization/index.ts
  src/api/authorization/login.ts
  src/api/authorization/logout.ts
  src/api/authorization/signup.ts
  src/api/comment/index.ts
  src/api/like/index.ts
  src/api/notification/index.ts
  src/api/post/index.ts
  src/api/post1/index.ts
  src/api/search/index.ts
  src/api/settings/index.ts
  src/api/user/index.ts
Labels: 리팩터링

#99 Feat/#98 global css
  src/assets/background.png
  src/index.css
  src/main.tsx
Labels: 기능

#90 Input Tag 컴포넌트 구현
  src/components/common/Input/InputStyles.ts
  src/components/common/Input/index.tsx
  src/stories/input.stories.tsx
Labels: 기능

#105 헤더, 인풋 컴포넌트 수정
  src/components/common/Header/headerStyle.ts
  src/components/common/Input/InputStyles.ts
  src/components/common/Input/index.tsx
Labels: 리팩터링

#111 router 주소 수정 작업
  src/routes/index.tsx
Labels: 리팩터링

#114 시간 관련 유틸 함수 구현
  package-lock.json
  package.json
  src/utils/getTimeFromNow.ts
  src/utils/index.ts
Labels: 기능

#115 회원 가입 / 로그인 페이지 구현
  src/api/authorization/login.ts
  src/components/common/Button/style.ts
  src/components/common/Input/InputStyles.ts
  src/components/common/Input/index.tsx
  src/components/signup/MbtiButton/index.tsx
  src/components/signup/MbtiButton/mbtiStyle.ts
  src/components/signup/SignUpForm/index.tsx
  src/components/signup/SignUpForm/signUpFormStyle.ts
  src/constants/loginConstants.ts
  src/constants/signUpConstants.ts
  src/hooks/useLocalStorage.ts
  src/pages/LoginPage/index.tsx
  src/pages/SignupPage/index.tsx
  src/types/signUpTypes.ts
Labels: 기능

#126 Post 페이지 구현
  src/pages/PostPage/PostCard.tsx
  src/pages/PostPage/PostCardList.tsx
  src/pages/PostPage/Tag.tsx
  src/pages/PostPage/TagList.tsx
  src/pages/PostPage/index.tsx
Labels: 기능

#122 루트 페이지(header, footer) 구현
  src/pages/RootPage/Footer.tsx
  src/pages/RootPage/Header.tsx
  src/pages/RootPage/index.tsx
Labels: 기능

#124 유저 정보 페이지 구현
  src/assets/user.svg
  src/pages/UserPage/Tag.tsx
  src/pages/UserPage/index.tsx
  src/pages/UserPage/style.ts
Labels: 기능

#127 내 정보 수정 페이지 구현
  src/pages/UserEditPage/Header.tsx
  src/pages/UserEditPage/Textarea.tsx
  src/pages/UserEditPage/index.tsx
  src/pages/UserEditPage/style.ts
Labels: 기능

#128 feat/#104_SearPage&404Page 구현
  src/assets/404_go_post.svg
  src/pages/Error404Page/index.tsx
  src/pages/SearchPage/Content/index.tsx
  src/pages/SearchPage/Footer.tsx
  src/pages/SearchPage/Header/index.tsx
  src/pages/SearchPage/Nav/index.tsx
  src/pages/SearchPage/SearchAPI.ts
  src/pages/SearchPage/UserCardStyle.tsx
  src/pages/SearchPage/index.tsx
Labels: 기능

#140 공통 api 로직 수정
  src/api/authorization/authorizationCheck.ts
  src/api/authorization/login.ts
  src/api/authorization/logout.ts
  src/api/authorization/signup.ts
  src/api/comment/index.ts
  src/api/index.ts
  src/api/like/index.ts
  src/api/notification/index.ts
  src/api/post/index.ts
  src/api/search/index.ts
  src/api/settings/index.ts
  src/api/user/index.ts
Labels: 버그

#134 refactor: 404페이지 리팩토링
  src/pages/Error404Page/index.tsx
  src/pages/SearchPage/Header.tsx
Labels: 리팩터링

#141 Search Page 리팩토링 완료
  src/pages/SearchPage/Content/index.tsx
  src/pages/SearchPage/Header/index.tsx
  src/pages/SearchPage/Nav/index.tsx
  src/pages/SearchPage/UserCardStyle.tsx
  src/pages/SearchPage/index.tsx
Labels: 리팩터링

#142 router 구조 수정
  src/pages/Layout/Footer.tsx
  src/pages/Layout/Header.tsx
  src/pages/Layout/index.tsx
  src/pages/RootPage/index.tsx
  src/pages/index.ts
  src/routes/index.tsx
Labels: 리팩터링

#146 개별페이지 리팩터링 (게시물작성, 알림, 비밀번호변경)
  src/pages/PostEditPage/index.tsx
  src/pages/UserPasswordPage/Button/index.tsx
  src/pages/UserPasswordPage/index.tsx
Labels: 리팩터링

#145 login을 form으로 구현
  src/pages/LoginPage/index.tsx
Labels: 기능

#148 Layout 페이지, Footer 컴포넌트 수정
  src/pages/Layout/Footer.tsx
  src/pages/Layout/index.tsx
Labels: 리팩터링

#151 User 타입 수정
  src/types/index.ts
Labels: 리팩터링

#154 refactor: Header Component 리팩토링
  src/assets/mainLogo.svg
  src/components/common/Header/headerStyle.ts
  src/components/common/Header/index.tsx
  src/index.css
  src/stories/header.stories.tsx
Labels: 리팩터링

#156 api 함수들의 반환 타입 수정
  src/api/authorization/authorizationCheck.ts
  src/api/authorization/login.ts
  src/api/authorization/logout.ts
  src/api/authorization/signup.ts
  src/api/comment/index.ts
  src/api/like/index.ts
  src/api/notification/index.ts
  src/api/post/index.ts
  src/api/search/index.ts
  src/api/settings/index.ts
  src/api/user/index.ts
Labels: 리팩터링

#169 유저 정보 페이지, 마이 페이지 구현
  src/pages/UserPage/PostCard.tsx
  src/pages/UserPage/PostCardStyle.ts
  src/pages/UserPage/index.tsx
  src/pages/UserPage/style.ts
Labels: 기능, 리팩터링

#171 회원가입/로그인 페이지 디자인 적용
  src/api/authorization/login.ts
  src/api/authorization/signup.ts
  src/assets/logoText.png
  src/components/common/Button/index.tsx
  src/components/common/Button/style.ts
  src/components/common/Input/InputStyles.ts
  src/components/common/Input/index.tsx
  src/components/signup/MbtiButton/index.tsx
  src/components/signup/MbtiButton/mbtiStyle.ts
  src/components/signup/SignUpForm/index.tsx
  src/constants/signUpConstants.ts
  src/pages/LoginPage/index.tsx
  src/pages/SignupPage/index.tsx
Labels: 버그, 스타일

#172 feat: top_nav_btn 컴포넌트 구현
  src/assets/top_nav_btn.svg
  src/components/common/TopNavBtn/index.tsx
  src/stories/TopNavBtn.stories.tsx
Labels: 기능

#173 Post 페이지 디자인 수정
  src/pages/PostPage/PostCard.tsx
  src/pages/PostPage/PostCardList.tsx
  src/pages/PostPage/TagList.tsx
  src/pages/PostPage/comment.svg
  src/pages/PostPage/heart.svg
Labels: 스타일

#174 Layout 페이지 디자인 수정
  src/pages/Layout/Footer.tsx
  src/pages/Layout/create.svg
  src/pages/Layout/login.svg
  src/pages/Layout/logo.svg
  src/pages/Layout/myInfo.svg
  src/pages/Layout/notification.svg
  src/pages/Layout/signup.svg
Labels: 스타일

#175 Header 컴포넌트 디자인 수정
  src/components/common/Header/back.svg
  src/components/common/Header/headerStyle.ts
  src/components/common/Header/index.tsx
  src/components/common/Header/search.svg
Labels: 기능

#181 내 정보 수정 페이지 구현
  src/pages/UserEditPage/Button.tsx
  src/pages/UserEditPage/index.tsx
  src/pages/UserEditPage/style.ts
Labels: 기능, 리팩터링

#185 게시물 상세보기 페이지 디자인 적용 및 버그수정
  src/components/postDetail/CommentCard/index.tsx
  src/components/postDetail/CommentCard/style.ts
  src/components/postDetail/Comments.tsx
  src/components/postDetail/PostDetail.tsx
  src/components/postDetail/commentStyle.ts
  src/components/postDetail/postDetailStyle.ts
  src/pages/PostDetailPage/index.tsx
Labels: 기능, 스타일

#186 Post 페이지 리팩터링 및 디자인 수정
  src/pages/PostPage/PostCard.tsx
  src/pages/PostPage/PostCard/index.tsx
  src/pages/PostPage/PostCard/style.ts
  src/pages/PostPage/PostCardList/index.tsx
  src/pages/PostPage/PostCardList/style.ts
  src/pages/PostPage/Tag/index.tsx
  src/pages/PostPage/TagList.tsx
  src/pages/PostPage/TagList/index.tsx
  src/pages/PostPage/TagList/style.ts
  src/pages/PostPage/assets/comment.svg
  src/pages/PostPage/assets/heart.svg
  src/pages/PostPage/index.tsx
Labels: 리팩터링, 스타일

#180 게시글 작성 페이지 디자인 작업
  src/pages/PostEditPage/Tag/index.tsx
  src/pages/PostEditPage/index.tsx
Labels: 스타일

#178 404 에러 페이지 디자인 및 기능 수정
  src/pages/Error404Page/index.tsx
  src/pages/Error404Page/planet.png
  src/pages/Error404Page/style.ts
Labels: 기능, 스타일

#187 비밀번호 변경 페이지 디자인 작업
  src/assets/passwordSeeIcon.svg
  src/pages/UserPasswordPage/Button/index.tsx
  src/pages/UserPasswordPage/Input/index.tsx
  src/pages/UserPasswordPage/index.tsx
Labels: 기능, 스타일

#189 design: Search_Page CSS 적용 및 오류 수정
  src/components/common/TopNavBtn/index.tsx
  src/pages/SearchPage/Content/index.tsx
  src/pages/SearchPage/Header.tsx
  src/pages/SearchPage/Header/index.tsx
  src/pages/SearchPage/UserCardStyle.tsx
Labels: 리팩터링, 스타일

#192 Layout 페이지, Footer, Header 컴포넌트 리팩터링 및 디자인 수정
  src/components/common/Footer/FooterStyle.ts
  src/components/common/Footer/assets/create.svg
  src/components/common/Footer/assets/index.ts
  src/components/common/Footer/assets/login.svg
  src/components/common/Footer/assets/logo.svg
  src/components/common/Footer/assets/myInfo.svg
  src/components/common/Footer/assets/notification.svg
  src/components/common/Footer/assets/signup.svg
  src/components/common/Footer/index.tsx
  src/components/common/Footer/style.ts
  src/components/common/Header/headerStyle.ts
  src/components/common/Header/index.tsx
  src/pages/Layout/Footer.tsx
  src/pages/Layout/Header.tsx
  src/pages/Layout/index.tsx
Labels: 리팩터링, 스타일

#193 Post 페이지 수정 작업
  src/pages/PostPage/PostCard/index.tsx
  src/pages/PostPage/PostCard/style.ts
  src/pages/PostPage/PostCardList/index.tsx
  src/pages/PostPage/index.tsx
Labels: 기능, 버그

#194 마이페이지(게시글, 자기소개), 유저 정보 페이지 디자인
  src/pages/UserPage/PostCard.tsx
  src/pages/UserPage/PostCardStyle.ts
  src/pages/UserPage/TopNavBtn.tsx
  src/pages/UserPage/assets/rocket.svg
  src/pages/UserPage/assets/spaceShip.svg
  src/pages/UserPage/assets/user_2.svg
  src/pages/UserPage/index.tsx
  src/pages/UserPage/style.ts
Labels: 스타일

#195 게시글 상세보기 페이지 변경
  src/components/postDetail/PostDetail.tsx
  src/pages/PostDetailPage/index.tsx
Labels: 버그

#190 알림페이지 디자인 작업
  src/pages/NotificationPage/NotificationCard.tsx
  src/pages/NotificationPage/NotificationCardList.tsx
  src/pages/NotificationPage/index.tsx
Labels: 스타일

#201 로그아웃 클릭시 루트 페이지로 이동
  src/components/common/Header/index.tsx
Labels: 긴급

#203 favicon 추가, title변경
  index.html
  public/vector.svg
  public/vite.svg
Labels: 스타일

#208 SearchPage 오류 및 일부 기능 수정
  src/components/common/UserCard/style.ts
  src/components/search/UserCard/UserCardGroup.tsx
  src/components/search/UserCard/index.tsx
  src/components/search/UserCard/style.ts
  src/pages/SearchPage/Content/index.tsx
  src/pages/SearchPage/Footer.tsx
  src/pages/SearchPage/Header/index.tsx
  src/pages/SearchPage/SearchAPI.ts
  src/pages/SearchPage/UserCardStyle.tsx
  src/pages/SearchPage/index.tsx
Labels: 리팩터링, 버그, 스타일

#204 댓글, 게시글 상세보기 너비값 조절
  src/components/postDetail/commentStyle.ts
  src/components/postDetail/postDetailStyle.ts
Labels: 버그

#213 PostCard, PostCardList 컴포넌트 폴더 경로 수정
  src/components/post/PostCard/index.tsx
  src/components/post/PostCard/style.ts
  src/components/post/PostCardList/index.tsx
  src/components/post/PostCardList/style.ts
  src/components/post/assets/comment.svg
  src/components/post/assets/heart.svg
  src/pages/PostPage/index.tsx
  src/pages/SearchPage/Content/index.tsx
Labels: 리팩터링

#217 댓글 입력창 높이 수정 및 폰트 변경
  src/components/postDetail/CommentInput.tsx
  src/components/postDetail/commentStyle.ts
Labels: 버그

#219 로딩 컴포넌트 추가
  src/components/common/Loading/crash.png
  src/components/common/Loading/index.tsx
  src/components/common/Loading/planet.png
  src/components/common/Spinner/index.tsx
Labels: 기능

#220 비 로그인 시 유저 정보를 볼 수 없었던 버그 수정
  src/pages/UserPage/PostCard.tsx
  src/pages/UserPage/Tag.tsx
  src/pages/UserPage/TopNavBtn.tsx
  src/pages/UserPage/index.tsx
  src/pages/UserPage/style.ts
Labels: 버그

#221 내 정보 수정 페이지 디자인
  src/pages/UserEditPage/Button.tsx
  src/pages/UserEditPage/Header.tsx
  src/pages/UserEditPage/Input.tsx
  src/pages/UserEditPage/InputStyle.ts
  src/pages/UserEditPage/Textarea.tsx
  src/pages/UserEditPage/assets/plus.svg
  src/pages/UserEditPage/index.tsx
  src/pages/UserEditPage/style.ts
Labels: 리팩터링, 스타일

#227 빌드를 위한 타입에러 문제 해결
  src/components/common/CommentCard/index.tsx
  src/components/common/CommentCard/style.ts
  src/components/common/PostCard/index.tsx
  src/components/common/PostCard/style.ts
  src/components/signup/MbtiButton/index.tsx
  src/pages/PostEditPage/post/index.ts
  src/pages/SearchPage/Content/index.tsx
  src/pages/UserPage/PostCard.tsx
  src/pages/UserPage/index.tsx
  src/stories/CommentCard.stories.tsx
  src/stories/PostCard.stories.tsx
  src/stories/UserCard.stories.tsx
  src/stories/input.stories.tsx
  src/types/index.ts
Labels: 버그

#232 모바일에서 너비가 넓게 출력되는 문제 해결
  src/components/signup/MbtiButton/mbtiStyle.ts
Labels: 버그

#228 Header, Footer 컴포넌트 디자인 수정
  src/components/common/Footer/FooterStyle.ts
  src/components/common/Footer/index.tsx
  src/components/common/Header/headerStyle.ts
Labels: 스타일

#233 Post 페이지 리팩터링 및 로딩 추가
  src/constants/channelId.ts
  src/pages/PostPage/TagList/style.ts
  src/pages/PostPage/index.tsx
Labels: 리팩터링

#237 assets 폴더 정리 작업
  src/assets/404_go_post.svg
  src/assets/add_button.svg
  src/assets/back_button.svg
  src/assets/background.png
  src/assets/logo.svg
  src/assets/logo_2.svg
  src/assets/search.svg
  src/assets/semiTitle.svg
  src/assets/semiTitle_2.svg
  src/assets/user.svg
Labels: 리팩터링

#230 알림페이지 반응형으로 수정 및 버그 fix
  src/pages/NotificationPage/NotificationCard.tsx
  src/pages/NotificationPage/index.tsx
  src/types/index.ts
Labels: 버그, 스타일

#235 SearchPage에 Loading 적용
  src/pages/SearchPage/Content/index.tsx
Labels: 리팩터링

#241 내 정보 수정 페이지 저장 시 loading 페이지 추가
  src/pages/UserEditPage/index.tsx
Labels: 기능

#242 게시글 작성 페이지 반응형으로 수정
  package.json
  src/pages/PostEditPage/PostEditPageStyle.ts
  src/pages/PostEditPage/index.tsx
Labels: 리팩터링, 버그

#247 공통 컴포넌트 Tag 병합
  src/components/common/Tag/index.tsx
Labels: 리팩터링

#249 게시글 작성 페이지 리팩터링
  src/api/post/index.ts
  src/pages/PostEditPage/Header/headerStyle.ts
  src/pages/PostEditPage/Header/index.tsx
  src/pages/PostEditPage/PostEditPageStyle.ts
  src/pages/PostEditPage/Tag/index.tsx
  src/pages/PostEditPage/index.tsx
  src/pages/PostEditPage/post/index.ts
Labels: 리팩터링

#254 게시글 작성페이지, 유저정보수정페이지,비밀번호 변경페이지 공통컴포넌트 (button, textarea) 병합 리팩터링
  src/components/common/Button/index.tsx
  src/components/common/Textarea/index.tsx
  src/pages/PostEditPage/Button/index.tsx
  src/pages/PostEditPage/Button/style.ts
  src/pages/PostEditPage/PostEditPageStyle.ts
  src/pages/PostEditPage/Textarea/index.tsx
  src/pages/UserEditPage/Button.tsx
  src/pages/UserEditPage/Textarea.tsx
  src/pages/UserEditPage/index.tsx
  src/pages/UserPage/index.tsx
  src/pages/UserPasswordPage/Button/index.tsx
  src/pages/UserPasswordPage/Button/style.ts
  src/pages/UserPasswordPage/index.tsx
Labels: 리팩터링

#255 Search 페이지의 Content, Header, 공통 컴포넌트 Loading 디자인 수정 작업
  src/components/common/Loading/index.tsx
  src/pages/SearchPage/Content/ContentStyle.ts
  src/pages/SearchPage/Content/index.tsx
  src/pages/SearchPage/Header/HeaderStyle.ts
  src/pages/SearchPage/Header/back.svg
  src/pages/SearchPage/Header/cancel.svg
  src/pages/SearchPage/Header/index.tsx
  src/pages/SearchPage/SearchPageStyle.ts
  src/pages/SearchPage/index.tsx
Labels: 스타일

#252 Post 페이지 리팩터링 작업
  src/components/post/TagList/index.tsx
  src/components/post/TagList/style.ts
  src/pages/PostPage/Tag/index.tsx
  src/pages/PostPage/index.tsx
Labels: 리팩터링

#257 #256 버그 해결
  src/components/postDetail/PostDetail.tsx
  src/components/postDetail/postDetailStyle.ts
Labels: 버그

#261 비밀번호 변경페이지 모바일 최적화 작업 및 깨짐현상 해결
  src/pages/UserPasswordPage/Input/index.tsx
  src/pages/UserPasswordPage/UserPasswordPageStyle.ts
  src/pages/UserPasswordPage/index.tsx
Labels: 리팩터링, 버그

#260 Modal 컴포넌트 추가 및 적용 작업
  src/components/common/Modal/index.tsx
  src/components/postDetail/CommentCard/index.tsx
  src/components/postDetail/Comments.tsx
  src/pages/LoginPage/index.tsx
  src/pages/NotificationPage/index.tsx
  src/pages/PostDetailPage/index.tsx
  src/pages/PostEditPage/index.tsx
  src/pages/SignupPage/index.tsx
  src/pages/UserPasswordPage/index.tsx
Labels: 기능

#259 핸드폰 기종 별 화면이 잘리던 문제 해결(scroll 문제)
  src/pages/UserEditPage/InputStyle.ts
  src/pages/UserEditPage/index.tsx
  src/pages/UserEditPage/style.ts
  src/pages/UserPage/index.tsx
  src/pages/UserPage/style.ts
Labels: 스타일

#263 feat: #262 알림, 비밀번호변경, 게시글작성 페이지 로딩 애니메이션 추가
  src/pages/NotificationPage/index.tsx
  src/pages/PostEditPage/PostEditPageStyle.ts
  src/pages/PostEditPage/index.tsx
  src/pages/UserPasswordPage/index.tsx
Labels: 기능, 스타일

#267 Post 페이지 리팩터링 및 무한스크롤 추가 작업
  src/pages/PostPage/PostPageStyle.ts
  src/pages/PostPage/getAllPosts.ts
  src/pages/PostPage/index.tsx
Labels: 기능

#271 회원 가입페이지 validation text가 모두 보였을때 상자가 작아지는 이슈
  src/components/signup/MbtiButton/mbtiStyle.ts
  src/pages/SignupPage/index.tsx
Labels: 기능

#268 TagList와 Header 컴포넌트 디자인 수정 작업
  src/components/common/Header/headerStyle.ts
  src/components/common/Header/index.tsx
  src/components/post/TagList/TagListStyle.ts
  src/components/post/TagList/index.tsx
Labels: 스타일

#270 리렌더링 시 userId의 변화를 감지, state(isMyInfo)를 초기화해주는 로직 추가, 내가 작성한 게시글 수가 많아지면 뒷 배경이 잘리는 에러 해결(높이 수정)
  src/pages/UserPage/index.tsx
  src/pages/UserPage/style.ts
Labels: 버그, 스타일

#274 Header 컴포넌트의 삭제버튼에 Modal 적용
  src/components/common/Header/index.tsx
Labels: 기능

#276 userPage에서 mbti의 3번째가 F일때 로켓의 위치 수정
  src/pages/UserPage/index.tsx
Labels: 스타일

#277 비밀번호 변경 페이지, 게시글 작성페이지 입력부분 useState 변경
  src/pages/PostEditPage/index.tsx
Labels: 리팩터링

#279 TagList 컴포넌트 디자인 수정
  src/components/post/TagList/index.tsx
  src/pages/PostPage/index.tsx
Labels: 스타일

#282 버셀 배포를 위한 설정파일 추가
  vercel.json
Labels: 기능

#283 Search 페이지, 비밀번호 변경페이지 수정
  src/pages/SearchPage/Content/index.tsx
  src/pages/UserPasswordPage/index.tsx
Labels: 긴급
